CREATE SEQUENCE SQ_CONTATOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_CONTATOS (
    ID INTEGER DEFAULT SQ_CONTATOS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    TELEFONE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);